spring.application.name=api-gateway

server.port=9080

# =========================================================
# CUSTOM JWT
# =========================================================

jwt.secret=ASsqb11Bh2B52uTCt3G24k+9mjthMjEjcdsockK2W+U=

# ============================================
# LOGIN SERVICE
# ============================================
spring.cloud.gateway.server.webmvc.routes[3].id=login-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:9081
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/auth/**

# ============================================
# USER SERVICE
# ============================================
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

# ============================================
# CLIENT SERVICE
# ============================================
spring.cloud.gateway.server.webmvc.routes[1].id=client-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/clients/**

# ============================================
# PROJECT SERVICE
# ============================================
spring.cloud.gateway.server.webmvc.routes[2].id=project-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:9084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/projects/**


# Tomcat/Servlet settings
server.servlet.context-path=/

# ======================================================
# ACTUATOR
# ======================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never

# ======================================================
# LOGGING
# ======================================================
logging.level.root=INFO
logging.level.com.insightzz=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# ERROR level explicitly aur stack trace print
logging.level.org.springframework.boot.web.servlet.support=ERROR


